services:
  - type: web
    name: forgebytex-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3001
    healthCheckPath: /health
